name: Build and Run

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: setup and run linter
      run: |
        pip install cpplint
        cpplint  --filter=-legal --linelength=100 *.cpp

    - name: tshirts fail
      run: |
        g++ -Wall -Wextra -Werror tshirts.cpp Test_Tshirt.cpp TshirtSizeClassifier.cpp -o tshirts.out
        bash ./tshirts.out

    - name: misaligned fail
      run: |
        g++ -Wall -Wextra -Werror misaligned.cpp Test_ColorMap.cpp GenerateColorMap.cpp -o misaligned.out
        bash ./misaligned.out

    - name: alerter fail
      run: |
        g++ -Wall -Wextra -Werror weatherreport.cpp Test_WeatherReport.cpp SensorStub.cpp WeatherReportGenerator.cpp -o weatherreport.out
        bash ./weatherreport.out
